spring:
  application:
    name: admin-service
  cloud:
    consul:
    ##注册中心ip地址
      host: localhost
     ##注册中心监听端口
      port: 8500
      discovery:
        register: true
        ##注册实例id
        instance-id: admin-service
    config:
          discovery:
            enabled: true
            service-id: config-service
          profile: dev
server:
     port: 19003

management:
  endpoint:
    health:
      show-details: always